### PR TITLE
Fix mode

### PR DESCRIPTION
**Pull request by josenavas**
@ElDeveloper you'll laugh about this one hahaha

It turns out that biom_open doesn't support that mode... fun fun

### CODE REVIEW

**Comment by mortonjt** [comment]
Should we open up a PR to fix that?

**Comment by josenavas** [comment]
@wasade?

**Comment by ElDeveloper** [comment]
👍

**Comment by wasade** [comment]
why were you trying to open the file for read and write?

**Comment by josenavas** [comment]
In HDF5, there is only 2 modes to open the file: 'r' read-only and 'r+' read-write: http://docs.h5py.org/en/latest/high/file.html#File.mode

**Comment by wasade** [comment]
guess an issue should be created :)

**Comment by wasade** [comment]
um... no, the full suite is supported (from the link you pasted):

"mode – Mode in which to open file; one of (“w”, “r”, “r+”, “a”, “w-”). See Opening & creating files."

and

```python
>>> import h5py
>>> f = h5py.File('modetest', 'w')
```

**Comment by josenavas** [comment]
Thanks @antgonza 

You're right @wasade - however, if you read down on the description of the "mode" parameter, it says that it will only be using r, or r+, but I guess it makes more sense to just use the w.

**Pull request merged**
