### PR TITLE
Minor spelling and/or grammar change

### PR DESCRIPTION
**Pull request by charles-cowart**
No rush.

### CODE REVIEW

**Comment by sjanssen2** [comment]
failing tests seem to stem from a simple flake8 thing

**Comment by antgonza** [comment]
yup, removed extra new line that is flake8 required ...

**Comment by charles-cowart** [comment]
FYI, there is code that fails flake8, but is not counted in the test:
support_files/sepp/tmpl_gg13.8-99_rename-json.py
support_files/sepp/tmpl_tiny_rename-json.py

**Comment by antgonza** [comment]
Good point! Wanna add it or leave as is, I'm OK either way ...

**Comment by sjanssen2** [comment]
I didn't add files like tmpl_gg13.8-99-revnamemap.json and the according *py, because those are generated by every SEPP (full, i.e. placements + tree generation) run from the reference tree/alignment/info file.

**Pull request merged**
