### PR TITLE
installing SEPP

### PR DESCRIPTION
**Pull request by antgonza**

### CODE REVIEW

**Comment by sjanssen2** [comment]
@antgonza I don't see how / where Java get's installed. Is that because Travis automatically comes with an installed Java?

**Comment by antgonza** [comment]
yup, like magic ...

**Comment by sjanssen2** [comment]
But that breaks when I install this plugin on my machine which does not automatically come with java. So I think we better require / install that somewhere explicitly.

**Comment by antgonza** [comment]
Good point, added in the README.

**Pull request merged**
