### PR TITLE
Silva 12.8

### PR DESCRIPTION
**Pull request by sjanssen2**
support for Silva 12.8 reference

### CODE REVIEW

**Comment by sjanssen2** [comment]
ready for reviews @antgonza @josenavas 
This is adding support for Silva as a non default reference tree into which deblur sequences can be placed.

**Comment by antgonza** [comment]
Code looks good, the only question is: should it be better that the references are discoverable? For example, that during __init__.py the plugin "searches" for files in support_files/sepp/reference/ and any foder in there (with that name) becomes an option? This will mean that in the future to add a new reference we only need to create and populate that folder. What do you think?

**Comment by sjanssen2** [comment]
@antgonza: that sounds like a nice mechanism. However, it is not that easy to only place files in there. 1) Siavash did a heavy compute on Exceed to create the reference tree/alignment/info from Silva and they get distributed with the underlying "fragment-insertion" conda package
2) I had to generate "rename" and "placement" templates from those three files.

Since the above process includes all those manual steps, the additional burden of extending the if condition is not too big and it safeguards us from adding wrong files or with wrong filenames / content.

All in all, adding another reference is not easy :-/

**Comment by antgonza** [comment]
Well, one option is to place all those files within the same folder, no? Now, perhaps it's worth exploring (as now we have 2 examples)how to merge (and even test) those rename/place templates. What do you think? Also, what will it take?

**Comment by antgonza** [comment]
closing due to inactivity and lack of benchmarks with Silva ...

**Pull request closed without merging**
